version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=production-secret-key-change-this
      - DB_PATH=./data/digiration.db